# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ebdaa8a78c6028c888933429f298853de9bd767836c5a547482cf88786aed4bccce5540b24bd3624125d3d6fcba31bba065e55b7c87b3e4b50f4125a5bc0fb35

test:
  secret_key_base: bb5f750e7598aebbca1f76422dfb34733254c98ce89f59edbb85534ebabe62525ae7abe9f237b818b884bb4233949d93fe34699a5d93ffaa7ad4db0cbb77e14b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
